### ISSUE TITLE
compilation to pdf failed .

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#8] opened 2021-04-06 12:43 UTC
I cannot solve this pb . seems the Tex compilation does not work.

**Comment by msdemlei** [comment] 2021-04-06 13:35
On Tue, Apr 06, 2021 at 05:43:47AM -0700, Mireille LOUYS wrote:
> I cannot solve this pb . seems the Tex compilation does not work. 

Could you be a bit more specific?  What are you trying to do, and
what is happening instead of what you are expecting?

If what doesn't work for you is the merge of PR #5, the problem is
that the repo contains a built PDF, which of course build-conflicts.

If you want, I can try to clean up the repo to do the merge -- should
I?

**Comment by BaptisteCecconi** [comment] 2021-04-07 07:44
yes, please do !

**Comment by BaptisteCecconi** [comment] 2021-04-07 08:59
Actually I solved this in #10 
I close this issue

**Closed by BaptisteCecconi** 2021-04-07 08:59 UTC
